# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:8.12


    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
        
      # run tests!
      - run: yarn test

      - run:
          name: "End-to-End Tests"
          command: |
            export FORCE_COLOR=1
            export BROWSERSTACK_PROJECT_NAME=5calls
            export BROWSERSTACK_BUILD_ID="CIRCLE:$CIRCLE_BUILD_NUM"

            # Start test server
            yarn start &
            SERVER_PID=$!
            # ...and wait for it to be ready
            echo 'Polling server until ready...'
            wget --retry-connrefused --no-check-certificate --no-verbose -T 60 localhost:3000
            echo ''

            # Actually do the tests
            yarn run web-tests:browserstack
            EXIT_CODE=$?

            # Stop server
            kill -9 $SERVER_PID
            exit $EXIT_CODE
